"""Core M5 forecasting pipeline shared by the Exercise 3 notebook and the Vertex AI trainer.

Generated by exercise3_m5_forecasting.ipynb (the `%%writefile m5_core.py` cell).
Edit the notebook cell and re-run it rather than editing this file by hand.

Contents
- load_m5 / price_matrix          : read the three Kaggle files into compact arrays
- build_summing_matrix / LEVELS   : the 12-level M5 hierarchy as a sparse summing matrix S
- WRMSSE                          : the official accuracy metric, evaluated on all 42,840 series
- FeatureBuilder                  : horizon-safe features (every sales feature is lagged >= 28 days)
- train_lgbm / predict_days       : global LightGBM (Tweedie) model
- seasonal_naive / ets_forecast   : benchmarks and upper-level statistical models
- fill_closed_days                : impute Christmas store closures for statistical models
- hierarchical_variants           : bottom-up vs. WLS-reconciled + middle-out forecasts
- make_submission                 : Kaggle submission frame
"""
import warnings

import numpy as np
import pandas as pd
from scipy import sparse

HORIZON = 28
ID_COLS = ["id", "item_id", "dept_id", "cat_id", "store_id", "state_id"]

# The 12 aggregation levels used by the M5 WRMSSE metric: level -> (name, grouping columns).
LEVELS = {
    1: ("Total", []),
    2: ("State", ["state_id"]),
    3: ("Store", ["store_id"]),
    4: ("Category", ["cat_id"]),
    5: ("Department", ["dept_id"]),
    6: ("State x Category", ["state_id", "cat_id"]),
    7: ("State x Department", ["state_id", "dept_id"]),
    8: ("Store x Category", ["store_id", "cat_id"]),
    9: ("Store x Department", ["store_id", "dept_id"]),
    10: ("Item", ["item_id"]),
    11: ("Item x State", ["item_id", "state_id"]),
    12: ("Item x Store", ["item_id", "store_id"]),
}


# --------------------------------------------------------------------------------------
# Data loading
# --------------------------------------------------------------------------------------
def load_m5(data_path):
    """Read the Kaggle files.

    Returns
    -------
    meta : DataFrame (n_series rows) with the id/hierarchy columns, in file order
    Y : float32 array (n_series, n_days) of unit sales, d_1 .. d_n
    calendar : DataFrame with an extra integer `d_num` column
    prices : DataFrame (store_id, item_id, wm_yr_wk, sell_price)
    """
    header = pd.read_csv(f"{data_path}/sales_train_evaluation.csv", nrows=0).columns
    day_cols = [c for c in header if c.startswith("d_")]
    sales = pd.read_csv(
        f"{data_path}/sales_train_evaluation.csv",
        dtype={**{c: np.int16 for c in day_cols}, **{c: str for c in ID_COLS}},
    )
    meta = sales[ID_COLS].reset_index(drop=True)
    Y = sales[day_cols].to_numpy(dtype=np.float32)
    del sales

    calendar = pd.read_csv(f"{data_path}/calendar.csv", parse_dates=["date"])
    calendar["d_num"] = calendar["d"].str[2:].astype(int)
    calendar = calendar.sort_values("d_num").reset_index(drop=True)

    prices = pd.read_csv(
        f"{data_path}/sell_prices.csv",
        dtype={"store_id": str, "item_id": str, "wm_yr_wk": np.int32, "sell_price": np.float32},
    )
    return meta, Y, calendar, prices


def price_matrix(meta, calendar, prices):
    """Weekly sell-price matrix (n_series, n_weeks) and the week index of every calendar day.

    A missing price means the item was not on sale in that store that week (e.g. before launch).
    """
    weeks = np.sort(calendar["wm_yr_wk"].unique())
    rows = pd.MultiIndex.from_frame(meta[["item_id", "store_id"]]).get_indexer(
        pd.MultiIndex.from_frame(prices[["item_id", "store_id"]])
    )
    cols = np.searchsorted(weeks, prices["wm_yr_wk"].to_numpy())
    keep = rows >= 0
    P_week = np.full((len(meta), len(weeks)), np.nan, np.float32)
    P_week[rows[keep], cols[keep]] = prices["sell_price"].to_numpy(np.float32)[keep]
    day_week = np.searchsorted(weeks, calendar["wm_yr_wk"].to_numpy())
    return P_week, day_week


# --------------------------------------------------------------------------------------
# Hierarchy and metric
# --------------------------------------------------------------------------------------
def build_summing_matrix(meta, levels=LEVELS):
    """Sparse 0/1 summing matrix S (n_all_series, n_bottom) and a frame describing each row.

    Row order: level 1 first, level 12 last. Level-12 rows are in the same order as `meta`,
    so S @ Y aggregates the bottom-level matrix to every node of the hierarchy at once.
    """
    blocks, info = [], []
    for level, (name, cols) in levels.items():
        if cols:
            key = meta[cols[0]].astype(str)
            for c in cols[1:]:
                key = key + "_" + meta[c].astype(str)
        else:
            key = pd.Series("Total", index=meta.index)
        codes, uniques = pd.factorize(key)
        blocks.append(
            sparse.csr_matrix(
                (np.ones(len(meta), np.float32), (codes, np.arange(len(meta)))),
                shape=(len(uniques), len(meta)),
            )
        )
        info.append(pd.DataFrame({"level": level, "level_name": name, "series": np.asarray(uniques)}))
    return sparse.vstack(blocks).tocsr(), pd.concat(info, ignore_index=True)


class WRMSSE:
    """M5 Weighted Root Mean Squared Scaled Error for the 28 days after `train_end`.

    - scale: mean squared one-step naive error of each series, from its first non-zero sale
      up to `train_end` (so series are comparable regardless of volume)
    - weight: dollar sales over the last 28 training days, normalised within each level,
      and every level counts 1/12 in the total
    """

    def __init__(self, Y, P_day, S, info, train_end, chunk=4000):
        self.S, self.info, self.train_end = S, info, train_end
        hist = Y[:, :train_end]
        self.actual = np.asarray(S @ Y[:, train_end:train_end + HORIZON], dtype=np.float64)

        scale = np.empty(S.shape[0])
        for start in range(0, S.shape[0], chunk):
            A = np.asarray(S[start:start + chunk] @ hist, dtype=np.float64)
            started = np.cumsum(A != 0, axis=1)[:, :-1] > 0
            d2 = np.diff(A, axis=1) ** 2
            scale[start:start + chunk] = (d2 * started).sum(1) / np.maximum(started.sum(1), 1)
        self.scale = np.where(scale > 0, scale, np.nan)

        dollars = np.nansum(hist[:, -HORIZON:] * P_day[:, train_end - HORIZON:train_end], axis=1)
        agg = np.asarray(S @ dollars, dtype=np.float64)
        level_total = pd.Series(agg).groupby(info["level"].to_numpy()).transform("sum").to_numpy()
        self.weights = agg / level_total

    def rmsse(self, pred_bottom):
        agg = np.asarray(self.S @ pred_bottom, dtype=np.float64)
        return np.sqrt(np.mean((self.actual - agg) ** 2, axis=1) / self.scale)

    def score(self, pred_bottom):
        """Return (overall WRMSSE, per-level WRMSSE Series indexed by level)."""
        contrib = np.nan_to_num(self.weights * self.rmsse(pred_bottom))
        per_level = pd.Series(contrib).groupby(self.info["level"].to_numpy()).sum()
        return float(per_level.mean()), per_level


# --------------------------------------------------------------------------------------
# Features
# --------------------------------------------------------------------------------------
LAGS = [28, 35, 42, 49, 56]
WINDOWS = [7, 14, 28, 56, 112]
STATIC_CATS = ["item_id", "dept_id", "cat_id", "store_id", "state_id"]
EVENT_CATS = ["event_name_1", "event_type_1", "event_name_2"]


def _cumsum0(A, dtype=np.float64):
    """Cumulative sum along days with a leading zero column: sum(A[:, a:b]) = C[:, b] - C[:, a]."""
    C = np.zeros((A.shape[0], A.shape[1] + 1), dtype)
    np.cumsum(A, axis=1, dtype=dtype, out=C[:, 1:])
    return C


def _window_sum(C, end, w):
    """Sum over the w days ending at 0-based day `end` (array); NaN where the window starts before day 0."""
    start = end - w + 1
    out = C[:, end + 1] - C[:, np.clip(start, 0, None)]
    out[:, start < 0] = np.nan
    return out


class FeatureBuilder:
    """Builds the LightGBM design matrix for any set of target days.

    Horizon-safe by construction: every feature derived from sales uses only days at least
    HORIZON (28) days before the target day. One model therefore forecasts all 28 days
    directly (no recursion, no error feedback), and a backtest sees exactly the information
    that is available when the real forecast is made. Calendar and price features are known
    in advance in M5 (calendar.csv and sell_prices.csv cover the forecast period).

    Rows are series-major (all target days of series 0, then series 1, ...) in `meta` order,
    so predictions reshape straight back to an (n_series, n_days) matrix.
    """

    def __init__(self, meta, Y, calendar, P_week, day_week):
        self.n, self.n_days = Y.shape
        self.Y = Y
        self.C = _cumsum0(Y)
        self.C2 = _cumsum0(np.square(Y, dtype=np.float64))
        self.Cz = _cumsum0((Y == 0).astype(np.float32), np.float32)

        self.codes = {c: pd.factorize(meta[c])[0].astype(np.float32) for c in STATIC_CATS}
        # Hierarchy-informed demand signals: the same item across all stores, and the
        # store x department it belongs to (average per series).
        self.group_of, self.group_C = {}, {}
        for name, cols in [("item", ["item_id"]), ("store_dept", ["store_id", "dept_id"])]:
            g = pd.factorize(meta[cols].astype(str).agg("_".join, axis=1))[0]
            G = sparse.csr_matrix((np.ones(self.n, np.float32), (g, np.arange(self.n))))
            mean = (G @ Y) / np.asarray(G.sum(axis=1))
            self.group_of[name], self.group_C[name] = g, _cumsum0(mean)

        cal = calendar.sort_values("d_num").reset_index(drop=True)
        self.calendar = cal
        self.wday = cal["wday"].to_numpy(np.float32)
        self.month = cal["month"].to_numpy(np.float32)
        self.mday = cal["date"].dt.day.to_numpy(np.float32)
        self.week = cal["date"].dt.isocalendar().week.to_numpy(np.float32)
        self.events = {}
        for c in EVENT_CATS:
            codes = pd.Categorical(cal[c]).codes.astype(np.float32)
            codes[codes < 0] = np.nan
            self.events[c] = codes
        states = pd.unique(meta["state_id"])
        snap = np.stack([cal[f"snap_{s}"].to_numpy(np.float32) for s in states])
        self.snap = snap[pd.Categorical(meta["state_id"], categories=states).codes]

        # Prices: daily matrix plus item-store level summaries.
        self.P_day = P_week[:, day_week]
        with warnings.catch_warnings():
            warnings.simplefilter("ignore", RuntimeWarning)
            self.p_max = np.nanmax(P_week, axis=1, keepdims=True)
            self.p_mean = np.nanmean(P_week, axis=1, keepdims=True)
        prev = np.concatenate([np.full((self.n, 1), np.nan, np.float32), P_week[:, :-1]], axis=1)
        self.p_momentum = (P_week / prev)[:, day_week]
        self.p_nunique = pd.DataFrame(P_week).nunique(axis=1).to_numpy(np.float32)[:, None]
        on_sale = ~np.isnan(P_week)
        first_week = np.where(on_sale.any(1), on_sale.argmax(1), P_week.shape[1]).astype(np.float32)
        self.weeks_since_release = day_week[None, :].astype(np.float32) - first_week[:, None]

        self.feature_names = [name for name, _ in self._columns(np.array([HORIZON]))]
        self.categorical_features = STATIC_CATS + EVENT_CATS

    def on_sale(self, days):
        """Boolean (n_series, len(days)) mask: item had a sell price that day."""
        return ~np.isnan(self.P_day[:, np.asarray(days) - 1])

    def _columns(self, t):
        """Yield (name, array) pairs; arrays are (n, T), (n, 1) or (T,) and broadcast to (n, T)."""
        for c in STATIC_CATS:
            yield c, self.codes[c][:, None]
        yield "wday", self.wday[t]
        yield "month", self.month[t]
        yield "mday", self.mday[t]
        yield "week", self.week[t]
        for c in EVENT_CATS:
            yield c, self.events[c][t]
        yield "snap", self.snap[:, t]

        price = self.P_day[:, t]
        yield "sell_price", price
        yield "price_rel_max", price / self.p_max
        yield "price_rel_mean", price / self.p_mean
        yield "price_momentum", self.p_momentum[:, t]
        yield "price_nunique", self.p_nunique
        yield "weeks_since_release", self.weeks_since_release[:, t]

        end = t - HORIZON  # last day a feature may look at (0-based)
        for lag in LAGS:
            src = t - lag
            col = self.Y[:, np.clip(src, 0, None)].copy()
            col[:, src < 0] = np.nan
            yield f"lag_{lag}", col
        for w in WINDOWS:
            yield f"rmean_{w}", _window_sum(self.C, end, w) / w
        s1, s2 = _window_sum(self.C, end, 28), _window_sum(self.C2, end, 28)
        yield "rstd_28", np.sqrt(np.clip((s2 - s1 ** 2 / 28) / 27, 0, None))
        yield "zero_frac_28", _window_sum(self.Cz, end, 28) / 28
        for name in ["item", "store_dept"]:
            group_mean = _window_sum(self.group_C[name], end, 28) / 28
            yield f"{name}_rmean_28", group_mean[self.group_of[name]]

    def make(self, days, require_target=True):
        """Design matrix for 1-based target `days`.

        require_target=True  -> training rows only: item on sale and the target is observed
        require_target=False -> every (series, day) row, for prediction
        Returns X (float32, rows x features), y (float32 or None), row mask (n, T).
        """
        t = np.asarray(days) - 1
        if (t - HORIZON).max() >= self.n_days:
            raise ValueError("target day too far ahead: features need sales up to 28 days before")
        T = len(t)
        if require_target:
            if t.max() >= self.n_days:
                raise ValueError("training days must have observed sales")
            mask = self.on_sale(days)
        else:
            mask = np.ones((self.n, T), bool)
        flat = mask.ravel()
        X = np.empty((int(flat.sum()), len(self.feature_names)), np.float32)
        for j, (_, arr) in enumerate(self._columns(t)):
            X[:, j] = np.broadcast_to(arr, (self.n, T)).ravel()[flat]
        y = self.Y[:, t].ravel()[flat] if require_target else None
        return X, y, mask


# --------------------------------------------------------------------------------------
# Models
# --------------------------------------------------------------------------------------
LGB_PARAMS = {
    "objective": "tweedie",  # zero-inflated, right-skewed counts; predicts the mean
    "tweedie_variance_power": 1.1,
    "metric": "rmse",
    "learning_rate": 0.05,
    "num_leaves": 255,
    "min_data_in_leaf": 100,
    "feature_fraction": 0.7,
    "bagging_fraction": 0.7,
    "bagging_freq": 1,
    "lambda_l2": 0.1,
    "max_bin": 255,
    "verbose": -1,
    "seed": 42,
}


def train_lgbm(fb, train_days, valid_days=None, params=None, num_boost_round=1500,
               early_stopping_rounds=100, log_period=100):
    """Fit the global LightGBM model on `train_days` (optionally early-stopping on `valid_days`)."""
    import lightgbm as lgb

    params = {**LGB_PARAMS, **(params or {})}
    X, y, _ = fb.make(train_days)
    dtrain = lgb.Dataset(X, y, feature_name=fb.feature_names,
                         categorical_feature=fb.categorical_features, free_raw_data=True)
    valid_sets, callbacks = [], [lgb.log_evaluation(log_period)]
    if valid_days is not None:
        Xv, yv, _ = fb.make(valid_days)
        valid_sets = [lgb.Dataset(Xv, yv, reference=dtrain)]
        callbacks.append(lgb.early_stopping(early_stopping_rounds, verbose=True))
    model = lgb.train(params, dtrain, num_boost_round=num_boost_round,
                      valid_sets=valid_sets, callbacks=callbacks)
    del X, y, dtrain
    return model


def predict_days(model, fb, days):
    """Forecast matrix (n_series, len(days)); zero where the item is not on sale."""
    X, _, _ = fb.make(days, require_target=False)
    pred = model.predict(X).reshape(fb.n, len(days))
    pred[~fb.on_sale(days)] = 0.0
    return np.clip(pred, 0, None).astype(np.float32)


def seasonal_naive(Y, train_end, horizon=HORIZON, season=7):
    """Repeat the last observed week."""
    return np.tile(Y[:, train_end - season:train_end], horizon // season).astype(np.float32)


def christmas_mask(calendar, n_days):
    """Boolean mask over d_1..d_n_days marking Christmas Day (stores closed)."""
    cal = calendar.sort_values("d_num").head(n_days)
    return ((cal["date"].dt.month == 12) & (cal["date"].dt.day == 25)).to_numpy()


def fill_closed_days(A, closed):
    """Replace days when stores were closed (Christmas) in each row of A (n, T) by the mean of
    the same weekday one week before and after, so a one-day closure does not distort the
    level, trend or seasonal estimates of statistical models. `closed` is a mask over the T days."""
    A = np.array(A, dtype=np.float64, copy=True)
    T = A.shape[1]
    for k in np.where(closed)[0]:
        nb = [j for j in (k - 7, k + 7) if 0 <= j < T]
        A[:, k] = A[:, nb].mean(axis=1)
    return A


def ets_forecast(series, horizon=HORIZON, closed=None, fit_days=728):
    """Damped-trend additive Holt-Winters with a weekly season, fitted to each row of `series`
    (n, T) over the last `fit_days` days. `closed` (mask over the T days) marks store closures."""
    from statsmodels.tsa.holtwinters import ExponentialSmoothing

    series = np.asarray(series, dtype=np.float64)[:, -fit_days:]
    if closed is not None:
        series = fill_closed_days(series, closed[-series.shape[1]:])
    out = np.zeros((series.shape[0], horizon))
    with warnings.catch_warnings():
        warnings.simplefilter("ignore")
        for i, y in enumerate(series):
            fit = ExponentialSmoothing(y, trend="add", damped_trend=True, seasonal="add",
                                       seasonal_periods=7, initialization_method="estimated").fit()
            out[i] = fit.forecast(horizon)
    return np.clip(out, 0, None)


# --------------------------------------------------------------------------------------
# Hierarchical reconciliation
# --------------------------------------------------------------------------------------
def upper_hierarchy(S, info, bottom_level=9):
    """Levels 1..bottom_level as their own hierarchy with Store x Dept nodes as the bottom.

    Returns (rows of S for levels <= bottom_level, S_up (n_upper, n_mid) 0/1 matrix,
    mid-level group index of every item-store series).
    """
    levels = info["level"].to_numpy()
    up_rows = np.where(levels <= bottom_level)[0]
    S_mid = S[np.where(levels == bottom_level)[0]]
    group_of = S_mid.tocsc().indices  # exactly one mid-level parent per item-store
    S_up = ((S[up_rows] @ S_mid.T).toarray() > 0).astype(np.float64)
    return up_rows, S_up, group_of


def reconcile_wls_struct(base, S_up):
    """WLS reconciliation with structural scaling: W = diag(number of bottom series per node).

    Returns coherent bottom-level (mid-level) forecasts G @ base, G = (S'W^-1 S)^-1 S'W^-1.
    """
    StW = S_up.T / S_up.sum(axis=1)
    G = np.linalg.solve(StW @ S_up, StW)
    return G @ base


def middle_out(pred_bottom, mid_forecast, group_of):
    """Split mid-level forecasts to item-stores in proportion to the bottom-level forecasts."""
    denom = np.zeros_like(mid_forecast, dtype=np.float64)
    np.add.at(denom, group_of, pred_bottom)
    ratio = np.divide(mid_forecast, denom, out=np.zeros_like(denom), where=denom > 0)
    return (pred_bottom * ratio[group_of]).astype(np.float32)


def hierarchical_variants(lgbm_bottom, Y, S, info, train_end, closed, ets_fit_days=728):
    """Bottom-level forecasts (n, 28) for each hierarchical strategy, plus the ETS upper forecasts."""
    up_rows, S_up, group_of = upper_hierarchy(S, info)
    S_upper = S[up_rows]
    ets_up = ets_forecast(S_upper @ Y[:, :train_end], closed=closed[:train_end], fit_days=ets_fit_days)
    lgb_up = np.asarray(S_upper @ lgbm_bottom, dtype=np.float64)
    variants = {"LightGBM bottom-up": lgbm_bottom}
    for name, base in [("ETS reconciled + middle-out", ets_up),
                       ("LightGBM+ETS reconciled + middle-out", 0.5 * (ets_up + lgb_up))]:
        mid = np.clip(reconcile_wls_struct(base, S_up), 0, None)
        variants[name] = middle_out(lgbm_bottom, mid, group_of)
    return variants, ets_up


# --------------------------------------------------------------------------------------
# Submission
# --------------------------------------------------------------------------------------
def make_submission(meta, Y, forecast):
    """Kaggle format: `_validation` rows hold the known d_1914..d_1941 actuals,
    `_evaluation` rows hold the 28-day forecast."""
    cols = [f"F{i}" for i in range(1, HORIZON + 1)]
    ids = meta["id"].astype(str)
    evaluation = pd.DataFrame(forecast, columns=cols)
    evaluation.insert(0, "id", ids.to_numpy())
    validation = pd.DataFrame(Y[:, -HORIZON:], columns=cols)
    validation.insert(0, "id", ids.str.replace("_evaluation", "_validation").to_numpy())
    return pd.concat([validation, evaluation], ignore_index=True)
